import { WorkoutDay, Exercise } from "./types";

export const EXERCISE_LIBRARY: Exercise[] = [
  // --- UPPER BODY COMPOUNDS (Target: 20 Reps) ---
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2-3 min",
    isBackSafe: true,
    muscleGroups: ["Chest", "Shoulders"],
    notes: "Keep back flat against the bench for stability.",
  },
  {
    id: "chest-supported-row",
    name: "Chest Supported Row (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Crucial for back safety. Avoid swinging.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown (Wide Grip)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Controlled eccentric. Don't lean back excessively.",
  },
  {
    id: "flat-db-press",
    name: "Flat Dumbbell Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2-3 min",
    isBackSafe: true,
    muscleGroups: ["Chest", "Shoulders"],
    notes: "Stable bench position. Focus on chest stretch.",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row (Chest Supported)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Use a chest pad if available to eliminate back strain.",
  },
  {
    id: "pull-ups",
    name: "Pull-Ups (Assisted)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Vertical pull is great for back width without loading.",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Chest", "Triceps"],
    notes: "High stability, zero back involvement.",
  },
  {
    id: "t-bar-row-supported",
    name: "Chest-Supported T-Bar Row",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Ensure chest stays on the pad throughout.",
  },
  {
    id: "shoulder-press-machine",
    name: "Seated Shoulder Press (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Shoulders", "Triceps"],
    notes: "Seated with back support is key.",
  },
  {
    id: "dips-assisted",
    name: "Assisted Dips",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Chest", "Triceps"],
    notes: "Lean forward for chest, stay upright for triceps.",
  },
  {
    id: "low-row-machine",
    name: "Low Row (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back", "Biceps"],
    notes: "Focus on pulling with elbows.",
  },

  // --- LOWER BODY COMPOUNDS (Target: 20 Reps) ---
  {
    id: "leg-press",
    name: "Leg Press (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Quads", "Glutes"],
    notes: "Keep lower back glued to the seat. Do not round at the bottom.",
  },
  {
    id: "hack-squat",
    name: "Hack Squat (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Quads", "Glutes"],
    notes: "Back is supported. If this feels heavy on back, use Leg Press.",
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Glutes", "Hamstrings"],
    notes: "Excellent glute builder with zero spinal loading.",
  },
  {
    id: "v-squat",
    name: "V-Squat (Machine)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Quads", "Glutes"],
    notes: "Face-in or face-out depending on machine, keep back neutral.",
  },
  {
    id: "goblet-squat-bench",
    name: "Goblet Squat (to Bench)",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Quads", "Glutes"],
    notes: "Bench acts as a depth guide and safety net.",
  },
  {
    id: "step-ups",
    name: "Weighted Step-Ups",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Quads", "Glutes"],
    notes: "Hold dumbbells at sides. Keep torso upright.",
  },

  // --- ISOLATION EXERCISES (Target: 30 Reps) ---
  {
    id: "leg-extension",
    name: "Leg Extension (Machine)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Quads"],
    notes: "Slow, controlled reps. Good for quad isolation.",
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl (Machine)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Hamstrings"],
    notes: "Replaces RDLs. Safer for the back while isolating hamstrings.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl (Machine)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Hamstrings"],
    notes: "Keep hips down on the pad.",
  },
  {
    id: "seated-lateral-raise",
    name: "Seated Lateral Raises",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Shoulders"],
    notes: "Seated prevents lower back momentum.",
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdowns (Cable)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60-90 sec",
    isBackSafe: true,
    muscleGroups: ["Triceps"],
    notes: "Keep elbows tucked.",
  },
  {
    id: "face-pulls",
    name: "Face Pulls (Cable)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Shoulders", "Upper Back"],
    notes: "Focus on rear delts and external rotation.",
  },
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curls",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps"],
    notes: "Bench support prevents cheating with the back.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raises",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Calves"],
    notes: "Hold the stretch at the bottom.",
  },
  {
    id: "back-extension",
    name: "Back Extension (45 Degree)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Lower Back", "Glutes", "Hamstrings"],
    notes: "Focus on glute/hamstring squeeze. Do not hyperextend.",
  },
  {
    id: "pec-deck",
    name: "Pec Deck (Machine Fly)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Chest"],
    notes: "Great for chest isolation without shoulder strain.",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Shoulders", "Upper Back"],
    notes: "Targets rear delts effectively.",
  },
  {
    id: "cable-crossover",
    name: "Cable Crossovers",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Chest"],
    notes: "Use a staggered stance for stability.",
  },
  {
    id: "preacher-curl-machine",
    name: "Preacher Curl (Machine)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps"],
    notes: "Fixed path prevents back involvement.",
  },
  {
    id: "overhead-tricep-ext",
    name: "Overhead Tricep Extension (Cable)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Triceps"],
    notes: "Use a rope attachment. Keep core tight.",
  },
  {
    id: "adductor-machine",
    name: "Adductor Machine",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Adductors"],
    notes: "Controlled squeeze.",
  },
  {
    id: "abductor-machine",
    name: "Abductor Machine",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Glutes"],
    notes: "Focus on outer glute engagement.",
  },
  {
    id: "hammer-curl-seated",
    name: "Seated Hammer Curls",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps", "Forearms"],
    notes: "Seated with back support to prevent swinging.",
  },
  {
    id: "spider-curl",
    name: "Spider Curls (Chest Supported)",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "90 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps"],
    notes: "Chest against incline bench. Pure isolation.",
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raises",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Shoulders"],
    notes: "Stand tall, keep core tight. Constant tension.",
  },
  {
    id: "rope-hammer-curl",
    name: "Cable Rope Hammer Curls",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps", "Forearms"],
    notes: "Keep elbows pinned to sides.",
  },
  {
    id: "single-arm-lat-pulldown",
    name: "Single Arm Lat Pulldown",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Back"],
    notes: "Allows for better lat contraction and focus.",
  },
  {
    id: "seated-shrug-machine",
    name: "Seated Shrug Machine",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Traps"],
    notes: "Seated prevents lower back involvement.",
  },
  {
    id: "cable-bicep-curl",
    name: "Seated Cable Bicep Curls",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps"],
    notes: "Sit on a bench to keep back stable.",
  },
  {
    id: "concentration-curl",
    name: "Concentration Curls",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Biceps"],
    notes: "Seated, leaning forward slightly, elbow against inner thigh.",
  },
  {
    id: "cable-tricep-ext-overhead",
    name: "Seated Cable Overhead Tricep Ext",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Triceps"],
    notes: "Sit on a bench with back support.",
  },
  {
    id: "bench-dips",
    name: "Bench Dips",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Triceps"],
    notes: "Keep back close to the bench.",
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Shoulders"],
    notes: "Back supported by machine seat.",
  },
  {
    id: "cable-front-raise",
    name: "Seated Cable Front Raise",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Shoulders"],
    notes: "Sit on a bench to isolate front delts.",
  },
  {
    id: "machine-fly",
    name: "Machine Chest Fly",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Chest"],
    notes: "Back pressed against the pad.",
  },
  {
    id: "cable-chest-press",
    name: "Seated Cable Chest Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Chest"],
    notes: "Sit on a bench for stability.",
  },
  {
    id: "machine-lat-pulldown-neutral",
    name: "Neutral Grip Lat Pulldown",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back"],
    notes: "Easier on shoulders, great for lats.",
  },
  {
    id: "machine-row-wide",
    name: "Wide Grip Machine Row",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back"],
    notes: "Targets upper back and rear delts.",
  },
  {
    id: "machine-leg-press-narrow",
    name: "Narrow Stance Leg Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Quads"],
    notes: "Focuses more on the quads.",
  },
  {
    id: "machine-leg-press-wide",
    name: "Wide Stance Leg Press",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "3 min",
    isBackSafe: true,
    muscleGroups: ["Glutes", "Adductors"],
    notes: "Focuses more on glutes and inner thighs.",
  },
  {
    id: "machine-glute-kickback",
    name: "Machine Glute Kickback",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Glutes"],
    notes: "Keep core tight to protect lower back.",
  },
  {
    id: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Glutes"],
    notes: "Hold onto the machine for stability.",
  },
  {
    id: "machine-calf-press",
    name: "Leg Press Calf Press",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Calves"],
    notes: "Done on the leg press machine.",
  },
  {
    id: "donkey-calf-raise-machine",
    name: "Donkey Calf Raise Machine",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Calves"],
    notes: "Back is supported by the pad.",
  },
  {
    id: "cable-crunch-seated",
    name: "Seated Cable Crunch",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Abs"],
    notes: "Sit on a bench, pull cable down with rope.",
  },
  {
    id: "machine-ab-crunch",
    name: "Machine Ab Crunch",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Abs"],
    notes: "Back is fully supported by the machine.",
  },
  {
    id: "seated-leg-raise",
    name: "Seated Leg Raises",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Abs"],
    notes: "Sit on the edge of a bench, lift legs.",
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Throughs",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Glutes", "Hamstrings"],
    notes: "Keep back flat, hinge at hips. Great for posterior chain without spinal loading.",
  },
  {
    id: "sissy-squat-machine",
    name: "Sissy Squat Machine",
    type: "isolation",
    sets: 3,
    targetReps: 30,
    rest: "60 sec",
    isBackSafe: true,
    muscleGroups: ["Quads"],
    notes: "Isolates quads perfectly. Keep core braced.",
  },
  {
    id: "chest-supported-tbar-row",
    name: "Chest-Supported T-Bar Row",
    type: "compound",
    sets: 3,
    targetReps: 20,
    rest: "2 min",
    isBackSafe: true,
    muscleGroups: ["Back"],
    notes: "Chest support removes lower back strain entirely.",
  },
];

export const WORKOUT_ROUTINE: WorkoutDay[] = [
  {
    id: "upper-a",
    title: "Upper A",
    focus: "Chest, Back, Shoulders",
    exercises: [
      EXERCISE_LIBRARY.find(e => e.id === "incline-db-press")!,
      EXERCISE_LIBRARY.find(e => e.id === "chest-supported-row")!,
      EXERCISE_LIBRARY.find(e => e.id === "lat-pulldown")!,
      EXERCISE_LIBRARY.find(e => e.id === "seated-lateral-raise")!,
      EXERCISE_LIBRARY.find(e => e.id === "tricep-pushdown")!,
    ],
  },
  {
    id: "lower-b",
    title: "Lower B",
    focus: "Hamstrings & Glutes (No RDLs)",
    exercises: [
      EXERCISE_LIBRARY.find(e => e.id === "seated-leg-curl")!,
      EXERCISE_LIBRARY.find(e => e.id === "hack-squat")!,
      EXERCISE_LIBRARY.find(e => e.id === "back-extension")!,
      EXERCISE_LIBRARY.find(e => e.id === "seated-calf-raise")!,
    ],
  },
  {
    id: "upper-b",
    title: "Upper B",
    focus: "Back, Chest, Arms",
    exercises: [
      EXERCISE_LIBRARY.find(e => e.id === "seated-cable-row")!,
      EXERCISE_LIBRARY.find(e => e.id === "flat-db-press")!,
      EXERCISE_LIBRARY.find(e => e.id === "pull-ups")!,
      EXERCISE_LIBRARY.find(e => e.id === "face-pulls")!,
      EXERCISE_LIBRARY.find(e => e.id === "incline-db-curl")!,
    ],
  },
  {
    id: "lower-a",
    title: "Lower A",
    focus: "Quads & Glutes (High Stability)",
    exercises: [
      EXERCISE_LIBRARY.find(e => e.id === "leg-press")!,
      EXERCISE_LIBRARY.find(e => e.id === "leg-extension")!,
      EXERCISE_LIBRARY.find(e => e.id === "hip-thrust")!,
      EXERCISE_LIBRARY.find(e => e.id === "seated-calf-raise")!,
    ],
  },
];
